#!/bin/bash

###########################################################################
#    Copyright (C) 2009 by Chris Jewell                                    #
#    chris.jewell@warwick.ac.uk                                            #
#                                                                          #
#    This program is free software; you can redistribute it and/or modify  #
#    it under the terms of the GNU General Public License as published by  #
#    the Free Software Foundation; either version 2 of the License, or     #
#    (at your option) any later version.                                   #
#                                                                          #
#    This program is distributed in the hope that it will be useful,       #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                          #
#                                                                          #
#    You should have received a copy of the GNU General Public License     #
#    along with this program; if not, write to the                         #
#    Free Software Foundation, Inc.,                                       #
#    59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
############################################################################


COUNTER=1

while((COUNTER<=25))
 do 
  mv fixedSims.$COUNTER.conf fixedSims.$COUNTER.conf.tmp;
  tail -n1 ss.$COUNTER.0.0.sim | awk '{ system("sed s/ObsTime=[0-9.]*/ObsTime=" $1 "/ fixedSims.'$COUNTER'.conf.tmp") }' > fixedSims.$COUNTER.conf;
 ((COUNTER++));
 done

exit(0)